### ISSUE TITLE
Emojis

### ISSUE THREAD

**Issue by Officialethnerd** [adraffy/ens-normalize.js#1]
where do these emojis fall?
0️⃣1️⃣2️⃣3️⃣4️⃣5️⃣6️⃣7️⃣8️⃣9️⃣🔟❎…and others?

**Comment by adraffy** [comment]
Those all are valid.

For reference, there are Digits `"1" [31]`, Digits w/emoji presentation `"1️" [31 FE0F]`, and Keycaps `"1️⃣" [31 FE0F 20E3]`.   Digits and Keycaps are valid.
