### ISSUE TITLE
List of supported emojis

### ISSUE THREAD

**Issue by djstrong** [adraffy/ens-normalize.js#11]
I have checked this emoji: https://adraffy.github.io/ens-normalize.js/test/emoji.html#q=%F0%9F%9B%A6

Is it just not synced with resolver or there is other issue?

**Comment by djstrong** [comment]
Ok, I see this "emoji" is not emoji: https://emojipedia.org/up-pointing-military-airplane/

**Comment by adraffy** [comment]
It's not an emoji.
