### ISSUE TITLE
ZWNJ are disallowed

### ISSUE THREAD

**Issue by bamnenim-kryptonium** [adraffy/ens-normalize.js#19]
string with zwnj fails to be normalized

![Screenshot 2023-05-30 at 1 10 24 PM](https://github.com/adraffy/ens-normalize.js/assets/95412790/949c3875-f60e-4b2f-b20d-c8ef8d91e616)

is this intended?

**Comment by adraffy** [comment]
Yes, https://github.com/adraffy/ensip-15/blob/master/ens-improvement-proposals/ensip-15-normalization-standard.md#derivation

**Comment by bamnenim-kryptonium** [comment]
Thanks!!
