### ISSUE TITLE
Name collision with process

### ISSUE THREAD

**Issue by Javarome** [adraffy/ens-normalize.js#23]
When building with Vite a web application that uses `ens-normalize` (typically indirectly through some `ethers` dependency) and a process polyfill, a runtime error occurs about the `process` identifier being already defined in the global scope:

<img width="857" alt="image" src="https://github.com/adraffy/ens-normalize.js/assets/2269113/79e3a077-6d87-405a-b6c3-2f36f240f8cb">

Indeed, `process` is both a [global NodeJS constant](https://nodejs.org/api/process.html) and a [global function in this package's code](https://github.com/adraffy/ens-normalize.js/blob/main/src/lib.js#L564). 

While I agree that including a (polyfilled) process dependency in a webapp is a bad idea, a number of libraries do this, and renaming or scoping the `process()` function might help integrating `ens-normalize` more easily in many environments.

**Comment by adraffy** [comment]
Ah, thanks.  I'll rename this function and double-check for any other node or related name collisions. 

I will update this thread again once I apply these changes.

**Comment by adraffy** [comment]
Is your project using the default Vite bundler?  This seems like a bug with esbuild.

**Comment by Javarome** [comment]
Yes default bundler. To reproduce, you can:
1. checkout the example [here](https://github.com/Arianee/arn-example/tree/ts_vite_2210)
2. npm install
1. npm run dev
1. open http://localhost:5173
1. check error in the the console

**Comment by adraffy** [comment]
Sorry for the delay.  [I renamed `process()`](https://github.com/adraffy/ens-normalize.js/blob/main/src/lib.js#L566) but it will be fixed in NPM on the 12th when I deploy the Unicode 15.1 update.

In the meantime, I have the following solution for your `vite.config.js`:
```ts
import { NodeGlobalsPolyfillPlugin } from '@esbuild-plugins/node-globals-polyfill'
import {defineConfig} from "vite"
import {readFile} from 'node:fs/promises'; // required import statement

export default defineConfig({
  optimizeDeps: {
    esbuildOptions: {
      define: {
        global: 'globalThis'
      },
      plugins: [
        {                                                                    //
          name: 'raffy-fix',                                                 // 
          setup(build) {                                                     // plugin
            build.onLoad({ filter: /ens-normalize/ }, async args => {        // that
              let contents = await readFile(args.path, {encoding: 'utf8'});  // renames
              contents = contents.replaceAll('process(', 'raffy_process(');  // process()
              return {contents};                                             // to
            });                                                              // raffy_process()
          },                                                                 //
        },                                                                   //
        NodeGlobalsPolyfillPlugin({buffer: true})
      ]
    }
  }
})
```

Alternatively, you could just skip adding this temporary plugin and enable `optimizeDeps.minifyIdentifiers: true`, which will mangle my function (but might cause issues with other libraries.)

**Comment by Javarome** [comment]
Indeed, it works this way. Can't wait for your latest version to be integrated in ethers! 
Thanks you!

**Comment by ricmoo** [comment]
Let me know when it’s published and I will make a patch release of ethers v6. :)

**Comment by adraffy** [comment]
This rename is active in the latest npm release 1.10.0
