### ISSUE TITLE
Synchronously importing the module causes perf heavy side-effects to run

### ISSUE THREAD

**Issue by jxom** [adraffy/ens-normalize.js#24]
It seems when I synchronously import `@adraffy/ens-normalize`, it causes some preparation side-effects to run: https://github.com/adraffy/ens-normalize.js/blob/main/src/lib.js#L172 

This causes a pretty large performance hit (especially on webpages for first load time).

Wonder if it could be possible to instead export the `init` function so folks can choose to eagerly initialize/prepare, and if it hasn't been prepared at time of fn call (e.g. `normalize_ens`) then run `init`?

**Comment by adraffy** [comment]
Ah, oops, that `init()` is not supposed to be there.  The new 1.10 release should have on-demand loading as you describe.   I'll fix this before I release the final 1.10 update with the Unicode 15.1.0 changes (sometime before end of week.)

**Comment by jxom** [comment]
Thank you!

**Comment by adraffy** [comment]
The latest npm release 1.10.0 has the delayed init feature.

I invested the init code a bit and made a few minor optimizations.  I'm seeing about ~200ms on weak hardware.  If this is still an issue, this can be significantly faster with a different data structure.  Additionally, the init could be delayed for specific ASCII input.
