### ISSUE TITLE
ens_beautify import issue from @adraffy/ens_normalize

### ISSUE THREAD

**Issue by mtxjwo** [adraffy/ens-normalize.js#3]
ens_beautify cannot not be resolved from @adraffy/ens_normalize, but it will resolve from @adraffy/ens_normalize/src/lib.js

Importing ens_beautify from @adraffy/ens_normalize results in import error therefore to import ens_beautify function the user must point to @adraffy/ens_normalize/src/lib

`import { ens_beautify } from "@adraffy/ens_normalize/src/lib"`

Testest on: Angular 2.0 v13.4

**Comment by adraffy** [comment]
Which version of `@adraffy/ens-normalize`?

Does `npm i @adraffy/ens-normalize@latest --save` fix the issue?  I might not be using semver correctly when I make a breaking change (previous beautify was a boolean option to ens_normalize.)

**Comment by mtxjwo** [comment]
It would be 1.5.6: 
`
    "@adraffy/ens-normalize": "^1.5.6",
`
I will update the package now to the latest.

**Comment by mtxjwo** [comment]
The package has been updated to 1.6.0 but it's encountered the same issue.

**Comment by adraffy** [comment]
Okay thanks. I will investigate.

**Comment by adraffy** [comment]
Oh, Angular must use the "browser" import.  I forgot to include the extra functions in "only-norm.js".  

This will be fixed in the next release.

**Comment by mtxjwo** [comment]
Thank you.

**Comment by adraffy** [comment]
This should be fixed in `1.6.1` — `package.json`/`"browser"` points to `"index.min.js"` instead of `"only-norm.js"`.

**Comment by mtxjwo** [comment]
Confirmed fixed and working on 1.6.1! Thanks a lot.

**Comment by mtxjwo** [comment]
Confirmed fixed and working on 1.6.1! Thanks a lot.
