### ISSUE TITLE
Beautified squared letters

### ISSUE THREAD

**Issue by djstrong** [adraffy/ens-normalize.js#9]
I am investigating names consisted of squared letters. However, for some letters theirs beautified version is different than others:
![image](https://user-images.githubusercontent.com/1849959/203002015-1a7714e8-bd95-4e20-befe-334305c7228b.png)
https://adraffy.github.io/ens-normalize.js/test/resolver.html#%F0%9F%85%B0%F0%9F%85%B1%F0%9F%85%B2%F0%9F%85%B3%F0%9F%85%B4%F0%9F%85%B5%F0%9F%85%B6%F0%9F%85%B7%F0%9F%85%B8%F0%9F%85%B9%F0%9F%85%BA%F0%9F%85%BB%F0%9F%85%BC%F0%9F%85%BD%F0%9F%85%BE%F0%9F%85%BF%F0%9F%86%80%F0%9F%86%81%F0%9F%86%82%F0%9F%86%83%F0%9F%86%84%F0%9F%86%85%F0%9F%86%86%F0%9F%86%87%F0%9F%86%88%F0%9F%86%89

Should it be somehow addressed in the library? You can disable beautifying those letters, but they also appear in other contexts (https://www.dictionary.com/e/emoji/b-button-emoji/).

**Comment by adraffy** [comment]
ABOP are emoji.  The rest are not.  I could demojify them if they neighbor another negative-squared but I'm not sure if that complexity is necessary.

**Comment by adraffy** [comment]
I posted about it here: https://discuss.ens.domains/t/ens-name-normalization-2nd/14564/53

Without a fairer way to resolve these characters, I think the current solution is the best we can do ATM.

Specifically for negative-squared, I want to keep the beautifier simple, so the above rendering is correct.
